// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHAxt8UKhhsEvsLXdzunJldWx-4sOkJ8E',
    appId: '1:73419662405:web:775a394887682e13392f2c',
    messagingSenderId: '73419662405',
    projectId: 'whatsapp-ai-agent-waseem',
    authDomain: 'whatsapp-ai-agent-waseem.firebaseapp.com',
    storageBucket: 'whatsapp-ai-agent-waseem.firebasestorage.app',
    measurementId: 'G-5H68SF3PHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXEkFSdB6CYXuBxwQaYbuQrqjCJ2w-l60',
    appId: '1:73419662405:android:91dc056dc3280258392f2c',
    messagingSenderId: '73419662405',
    projectId: 'whatsapp-ai-agent-waseem',
    storageBucket: 'whatsapp-ai-agent-waseem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUbH4sPnF1XLxu4Lov05NGKEbJNZC4tp4',
    appId: '1:73419662405:ios:170ab7b5bf8e9ef6392f2c',
    messagingSenderId: '73419662405',
    projectId: 'whatsapp-ai-agent-waseem',
    storageBucket: 'whatsapp-ai-agent-waseem.firebasestorage.app',
    iosClientId:
        '73419662405-ddn58887ad2uuduph58seamteorta7vc.apps.googleusercontent.com',
    iosBundleId: 'com.sanayed.tulipAlerts',
  );
}
