import 'dart:typed_data';

import 'package:flutter/material.dart';

import '../l10n/generated/app_localizations.dart';
import '../services/export_service.dart';

enum ExportKind { excel, pdf, email }

/// Compact export control used by both tabs — a single icon that opens a
/// menu, so neither screen gains a row of competing buttons.
class ExportMenu extends StatefulWidget {
  const ExportMenu({
    super.key,
    required this.onExport,
    this.showExcel = true,
    this.showPdf = true,
  });

  /// Returns a short error key, or null on success.
  final Future<String?> Function(ExportKind kind, String? emailTo) onExport;

  final bool showExcel;
  final bool showPdf;

  @override
  State<ExportMenu> createState() => _ExportMenuState();
}

class _ExportMenuState extends State<ExportMenu> {
  bool _busy = false;

  Future<void> _run(ExportKind kind) async {
    final l = AppLocalizations.of(context);
    final messenger = ScaffoldMessenger.of(context);

    String? emailTo;
    if (kind == ExportKind.email) {
      emailTo = await _askRecipient();
      if (emailTo == null || emailTo.isEmpty) return;
    }

    setState(() => _busy = true);
    messenger.showSnackBar(SnackBar(
      content: Text(l.exportPreparing),
      duration: const Duration(seconds: 1),
    ));

    final error = await widget.onExport(kind, emailTo);
    if (!mounted) return;
    setState(() => _busy = false);

    messenger.showSnackBar(SnackBar(
      content: Text(switch (error) {
        null => kind == ExportKind.email ? l.emailSent : l.exportDone,
        'not_configured' => l.emailNotConfigured,
        _ => '${l.exportFailed} — $error',
      }),
      duration: const Duration(seconds: 3),
    ));
  }

  Future<String?> _askRecipient() {
    final l = AppLocalizations.of(context);
    final controller = TextEditingController();
    return showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(l.emailDialogTitle),
        content: TextField(
          controller: controller,
          autofocus: true,
          keyboardType: TextInputType.emailAddress,
          decoration: InputDecoration(labelText: l.emailFieldLabel),
          onSubmitted: (v) => Navigator.of(context).pop(v.trim()),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: Text(l.cancel),
          ),
          FilledButton(
            onPressed: () => Navigator.of(context).pop(controller.text.trim()),
            child: Text(l.emailSend),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);

    if (_busy) {
      return const Padding(
        padding: EdgeInsets.all(14),
        child: SizedBox(
          width: 18,
          height: 18,
          child: CircularProgressIndicator(strokeWidth: 2),
        ),
      );
    }

    return PopupMenuButton<ExportKind>(
      tooltip: l.exportTitle,
      icon: const Icon(Icons.ios_share, size: 20),
      onSelected: _run,
      itemBuilder: (context) => [
        if (widget.showExcel)
          PopupMenuItem(
            value: ExportKind.excel,
            child: ListTile(
              dense: true,
              contentPadding: EdgeInsets.zero,
              leading: const Icon(Icons.table_chart_outlined, size: 20),
              title: Text(l.exportExcel),
            ),
          ),
        if (widget.showPdf)
          PopupMenuItem(
            value: ExportKind.pdf,
            child: ListTile(
              dense: true,
              contentPadding: EdgeInsets.zero,
              leading: const Icon(Icons.picture_as_pdf_outlined, size: 20),
              title: Text(l.exportPdf),
            ),
          ),
        PopupMenuItem(
          value: ExportKind.email,
          child: ListTile(
            dense: true,
            contentPadding: EdgeInsets.zero,
            leading: const Icon(Icons.mail_outline, size: 20),
            title: Text(l.exportEmail),
            subtitle: ExportService.isEmailConfigured
                ? null
                : Text(
                    l.emailNotConfigured,
                    style: const TextStyle(fontSize: 10),
                  ),
          ),
        ),
      ],
    );
  }
}

/// Convenience holder so callers can pass generated bytes around.
class ExportPayload {
  const ExportPayload({
    required this.bytes,
    required this.filename,
    required this.mimeType,
  });

  final Uint8List bytes;
  final String filename;
  final String mimeType;
}
